### Get all reviews
GET http://localhost:4004/odata/v4/catalog/Reviews
Authorization: Basic YWxpY2U6YWxpY2U=

### Get Dune review
GET http://localhost:4004/odata/v4/catalog/getBookReview(book_id=101)
Authorization: Basic YWxpY2U6YWxpY2U=

### Get 1984 review
GET http://localhost:4004/odata/v4/catalog/getBookReview(book_id=102)
Authorization: Basic YWxpY2U6YWxpY2U=